# Generated by Django 6.0 on 2025-12-07 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='restaurant',
            fields=[
                ('id_restaurant', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('stars', models.IntegerField()),
                ('tables', models.IntegerField()),
                ('capacity', models.IntegerField()),
            ],
        ),
    ]
